name: Re-build everything

# Let's the dependabot rebuild all the build files against the most latest Tailwind CSS version
# Hopefully this doesn't get out of hand!

on: pull_request

jobs:
  build_and_process:
    name: Build and Process
    if: github.actor == 'dependabot-preview[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Tailwind CSS
        run: npm ci
      - name: Build all Tailwind configs!
        shell: bash
        run: |
          for c in $(find configs -not -name '*.json'); do
            if [[ -f $c ]]; then
              config=${c%%.*}; npx tailwindcss build style.css -o builds/${config#configs/}.css -c $c;
            fi;
          done
      - name: Commit files into build folder
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add Build file
      - name: Merge into master
        uses: "pascalgn/automerge-action@v0.11.0"
        env:
          MERGE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_DELETE_BRANCH: true
          GITHUB_TOKEN: "${{ secrets.PA_TOKEN }}"
