name: Auto Tag

on:
  push:
    branches: master

jobs:
  tailwind_tag_plus_increment:
    name: Make Release based on Tailwind CSS version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Only run if build files changed
        id: git-diff-build
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            +(builds)/**/*.css
      - name: Install Tailwind CSS
        if: steps.git-diff-build.outputs.count != 0
        run: |
          npm ci
          echo ${{ steps.git-diff-build.outputs.diff }}
          echo "TAILWIND_VERSION=$(npm view tailwindcss version)" >> $GITHUB_ENV
      - name: Tag with Tailwind CSS version prepended
        if: steps.git-diff-build.outputs.count != 0
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.TAILWIND_VERSION }}-0-1-0-${{ github.run_id }}-${{ github.run_number }}
          release_name: v${{ env.TAILWIND_VERSION }}-0-1-0-${{ github.run_id }}-${{ github.run_number }}
          draft: false
          prerelease: false
