name: Validate, Build, and Merge

# Check that there is only one config file added, optionally in a folder
# Check that the file is a valid tailwind config file
# Build the config, then re-commit to this PR branch
# If all goes well, merge into master

on:
  push:
    branches: master

jobs:
  build_and_process:
    name: Build and Process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Tailwind CSS
        run: |
          npm ci
      - name: Determine Build Files
        shell: bash
        run: |
          # Multiple files changed, rebuild everything (possible improvement would be to check specific changes, config/package.json, etc)
          if [[ $(git diff --name-only | grep configs* | wc -l) != 1 ]; then
            echo "REBUILD_ALL=1" >> $GITHUB_ENV
          fi
          # Another improvment would be to check whether multiple files only in config were added, then only build those
      - name: Validate Config File
        shell: bash
        run: |
          CONFIG_FILE=$(git diff --diff-filter=A --name-only `git merge-base origin/master HEAD`)
          node validate.js $CONFIG_FILE
      - name: Build Tailwind Single Config
        shell: bash
        if: ${{ env.REBUILD_ALL }}
        run: |
          CONFIG_FILE=$(git diff --diff-filter=A --name-only `git merge-base origin/master HEAD`)
          OUTPUT_FILE="builds/"
          OUTPUT_FILE+=${CONFIG_FILE#"configs/"}
          OUTPUT_FILE=${OUTPUT_FILE%.*}.css
          npx tailwindcss build style.css -o $OUTPUT_FILE -c $CONFIG_FILE
      - name: Build Tailwind Multiple Config
        shell: bash
        if: ${{ !env.REBUILD_ALL }}
        run: |
          # Build everything in config
          for c in $(find configs -not -name '*.json'); do
            if [[ -f $c ]]; then
              config=${c%%.*}; npx tailwindcss build style.css -o builds/${config#configs/}.css -c $c;
            fi;
          done
      - name: Commit files into build folder
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add Build
