name: Validate, Build, and Merge

# Check that there is only one config file added, optionally in a folder
# Check that the file is a valid tailwind config file
# Build the config, then re-commit to this PR branch
# If all goes well, merge into master

on:
  push:
    branches: master

jobs:
  build_and_process:
    name: Build and Process
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PA_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install Tailwind CSS
        run: |
          npm ci
      - name: Check Config Changes
        id: git-diff-config
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            +(configs)/**/*.js
      - name: Check Build Changes
        id: git-diff-build
        uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            +(builds)/**/*.css
      - name: Validate Config File
        shell: bash
        if: steps.git-diff-config.outputs.count == 1 && steps.git-diff-build.outputs.count == 0
        run: |
          CONFIG_FILE=${{ steps.git-diff-config.outputs.diff }}
          node validate.js $CONFIG_FILE
      - name: Build Tailwind Single Config
        shell: bash
        if: steps.git-diff-config.outputs.count == 1 && steps.git-diff-build.outputs.count == 0
        run: |
          CONFIG_FILE=${{ steps.git-diff-config.outputs.diff }}
          OUTPUT_FILE="builds/"
          OUTPUT_FILE+=${CONFIG_FILE#"configs/"}
          OUTPUT_FILE=${OUTPUT_FILE%.*}.css
          npx tailwindcss build style.css -o $OUTPUT_FILE -c $CONFIG_FILE
      - name: Build Tailwind Multiple Config
        shell: bash
        if: steps.git-diff-config.outputs.count != 1 && steps.git-diff-build.outputs.count == 0
        run: |
          # Build everything in config
          for c in $(find configs -not -name '*.json'); do
            if [[ -f $c ]]; then
              config=${c%%.*}; npx tailwindcss build style.css -o builds/${config#configs/}.css -c $c;
            fi;
          done
      - name: Commit files into build folder
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Add Build
